### ISSUE TITLE
" Building wheel for pdf-to-csv-script (setup.py) ... error"

### ISSUE THREAD

**Issue by ddan1218** [DanielPDWalker/pdf_to_csv_script#1]
Hello:
I received the following while building 'pdf_to_csv_script'.

> Building wheels for collected packages: pdf-to-csv-script
>   Building wheel for pdf-to-csv-script (setup.py) ... error
>   ERROR: Command errored out with exit status 1:
>    command: /home/david/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_1na_6q8/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_1na_6q8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-i7fok7rs
>        cwd: /tmp/pip-req-build-_1na_6q8/
>   Complete output (6 lines):
>   usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>      or: setup.py --help [cmd1 cmd2 ...]
>      or: setup.py --help-commands
>      or: setup.py cmd --help
>   
>   error: invalid command 'bdist_wheel'
>   ----------------------------------------
>   ERROR: Failed building wheel for pdf-to-csv-script
>   Running setup.py clean for pdf-to-csv-script
> Failed to build pdf-to-csv-script

Thank you for working on this.  I am not a programmer.  I found your script while searching for a way to convert pdf to csv so I can assist my wife in examination of 3100 pages of tables from the 55000 page Pfizer document dump (pdf) that you may have heard about on the news.  I need to be able to get these tables into a spread sheet.  Any suggestions would be most appreciated.  I attach a screenshot of page 1.  Thank you.
![Picture of table from Pfizer](https://user-images.githubusercontent.com/100368394/163679604-d50913fa-c76a-460d-b2a3-904fdcc66aa3.png)
.

**Comment by DanielPDWalker** [comment]
Hey @ddan1218, just a heads up this was something I threw together very quickly so not widely tested and kinda of built for one specific purpose, but I'm happy to try and get this working for you.

First a couple of questions: What operating system are you on? What version of python are you using? (You can find this out by typing either `python --version` or `python3 --version` depending on your system).



Edit: Doing the following might help you:

Delete your old virtual environment.
Create and activate a new virtual environment. (Or if you are using your system python just do the following).

`python -m pip install --upgrade pip`
`pip install wheel`

The above commands updates pip and wheel both of which help python install and manage packages (like this one). Sometimes if they are out of date they can cause some weird issues.

Then go through the normal install of the package.

**Comment by ddan1218** [comment]
Thanks for all your efforts @DanielPDWalker!

I did my best to follow your instructions and this was returned:

> Building wheels for collected packages: pdf-to-csv-script
>   Building wheel for pdf-to-csv-script (setup.py) ... error
>   ERROR: Command errored out with exit status 1:
>    command: /home/david/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-1m3w3cqu/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-1m3w3cqu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-57buivr6
>        cwd: /tmp/pip-req-build-1m3w3cqu/
>   Complete output (6 lines):
>   usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>      or: setup.py --help [cmd1 cmd2 ...]
>      or: setup.py --help-commands
>      or: setup.py cmd --help
>   
>   error: invalid command 'bdist_wheel'
>   ----------------------------------------
>   ERROR: Failed building wheel for pdf-to-csv-script

I am using Python 3.8.10.

My computer: 
> System:    Kernel: 5.4.0-107-generic x86_64 bits: 64 compiler: gcc v: 9.4.0 Desktop: Cinnamon 5.2.7 wm: muffin 5.2.1 
>            dm: LightDM 1.30.0 Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 

Again, thanks for your interest.
In that regard, the project for which I had intended to use your program (my personal need has abated) is this one: [Pfizer Documents Analysis - WarRoom  
](https://campaigns.dailyclout.io/campaign/brand/cc3b3e5a-6536-4738-8ed6-5ee368c67240)  Should you have the time and inclination, my guess is that someone with your skills would be most welcome.  It is all volunteer work.

Thank you again for your interest.

**Comment by DanielPDWalker** [comment]
In case anyone else finds this and cant get my script working, here is a link to other ways to get data out of pdfs: https://academy.datawrapper.de/article/135-how-to-extract-data-out-of-pdfs
